spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 5MB
      max-file-size: 300MB
      max-request-size: 300MB

aws:
  s3:
    region: ap-southeast-2
    bucket: campidelli-file-storage-service-bucket
    createBucketIfNotExist : true
    multipart:
      throughputInGbps: 20.0
      minimumPartSizeInMb: 8

server:
  port: 8080
  error:
    include-message: always

logging:
  level:
    root: info
    campidelli: warn
